---
title: "Replication of Koenders et al., 2016 via OpenNeuro Public Dataset (2016, PLOS One)"
author: "Justin Yuan (yuanjp@stanford.edu)"
date: "`r format(Sys.time(), '%B %d, %Y')`"
output:
  html_document:
    toc: yes
    toc_depth: 3
    toc_float:
      collapsed: false
---

# Introduction
## Justification for experiment
This study examines structural brain changes in young adult cannabis users in a longitudinal design. This study is pertinent to my research interests because I will be studying structural-functional relationships in adolescent brain development using similar neuroimaging methods. It will be beneficial to have experience with this structural processing pipeline and with SPM software.

## Description of paper
The study by Koenders et al. examined whether structural brain changes were associated with substance use (focusing on cannabis) over a three-year period. The participants of the study were young adult users and matched healthy controls. The study used a magnetic resonance imaging (MRI) technique called voxel-based morphometry (VBM) to measure grey matter volume (GMV) changes. They assessed drug usage with questionnaires for nicotine, alcohol, and cannabis usage. 

I aim to replicate the study’s finding of significant cerebellar differences between users and healthy controls at baseline using the authors’ voxel-based morphometry pipeline and two-sample t-tests.

## Description of stimuli and procedures
I will be using the subject T1-weighted MRI baseline and follow-up scan data from OpenNeuro. (https://openneuro.org/datasets/ds000174/versions/1.0.1). SPM8 software will be used to conduct voxel-based morphometry analysis (using VBM8 of SPM).

## VBM Procedure Overview:

1. Normalization
2. Segmentation of T1w data into grey matter, white matter, and CSF
3. Smoothing of voxels
4. Statistical analysis

## Anticipated Challenges
- Reproducing the VBM pipeline steps when explicit parameter values are not listed
- Possible software incompatability with SPM8
- May need to use SPM12 instead of SPM8

## Links
Project Repository: https://github.com/psych251/koenders2016

Original Paper: https://github.com/psych251/koenders2016/tree/master/original_paper

## Methods

### Power Analysis

*Original effect size, power analysis for samples to achieve 80%, 90%, 95% power to detect that effect size.  Considerations of feasibility for selecting planned sample size.*

### Planned Sample

The sample for this pipeline reproduction consists of heavy cannabis users (CB,n=20, age baseline M=20.5, SD=2.1) and non-cannabis using healthy controls (HC,n=22 age baseline M=21.6, SD=2.45). T1-weighted MRI data comes from OpenNeuro.org.

### Materials
The materials required for this VBM pipeline reproduction are 1) the MRI dataset and 2) neuroimaging processing software. Both are available online and summarized below:

1. MRI dataset - 3T structural MRI scans were downloaded from OpenNeuro with the parameters as follows: T1 turbo field echo, TR 9.6 s, TE 4.6 s, 182 slices, slice thickness 1.2 mm, FOV 256x256 mm, in-plane resolution 256x256mm, flip angle 8°. See Links section for OpenNeuro source.

2. SPM software - the pipeline will be run in SPM8 (Structural Brain Mapping Group), specifically employing the VBM-8 module. SPM requires Matlab.

**Replication study differences:**
Dependent on software compatability, SPM12 may be used instead of SPM8.

### Procedure	
**Voxel-based morphometry**  
*Quoted from study:*
"For both the cross-sectional and the longitudinal analyses, we used the VBM-8 module of
the software package SPM (Structural Brain Mapping Group, University of Jena, Germany,
http://dbm.neuro.uni-jena.de/vbm8). For the cross-sectional analyses, at baseline and followup,
individual T1 images were first aligned to a T1 template in MNI-space (Montreal Neurological Institute) and subsequently segmented into grey matter, white matter and cerebro-
spinal fluid. The resulting grey matter was normalized using the diffeomorphic image registration
algorithm (DARTEL) [33]. Grey matter images were modulated with the nonlinear
transformation parameters as computed during the normalization procedures. The resulting
images contain the volume proportion of probabilistically assigned grey matter tissue for
each voxel. These grey matter tissue probability images were visually inspected again and
finally smoothed with an 8-mm Gaussian kernel. Note that each image of the regional grey
matter volume was corrected for individual brain size, since this step is part of the VBM8
toolbox routine."

**ROIs**  
The study examined specific regions of interest (ROIs) that were based on previous cross-sectional findings. They were anatomically defined using the Nielsen and Hansen’s volume of interest online database. The ROIs were the: OFC, ACC, insula, striatum, thalamus, amygdala, hippocampus and cerebellum

**Replication Study Differences:**  
SPM12 may be used for the VBM processing pipeline instead of SPM8 due to possible incompatabilities of the older SPM8 / VBM-8 module and the current version of Matlab 2019a. If SPM12 is employed, the CAT12 VBM module will be used instead of VBM-8.

This replication will focus on the cerebellum ROI as it was the primary baseline finding.

### Analysis of VBM Data

The key analysis of interest is a two-sample t-test of the grey matter volumes at baseline between the cannabis users group and the healthy control group. The result of interest is a significant difference of GMV located at the cerebellum between users and controls.

In addition to the two-sample t-test, I will check the cerebellar ROI's grey matter volumes for normality.

Significance was defined as follows:
"For all analyses, we first performed region of interest ROI analyses, where structural differences within ROI masks were considered significant if p < .001, with an FWE-corrected cluster probability of p < .05 adjusted for the small search volume [36].

### Differences from Original Study

The main difference between this pipeline reproduction and the original study is the possible usage of SPM12. This possibility is not likely as it should be straightforward to resolve incompatabilities by using an older version of Matlab (e.g. one released around SPM8 like R2014b).

### Methods Addendum (Post Data Collection)

You can comment this section out prior to final report with data collection.

#### Actual Sample
  Sample size, demographics, data exclusions based on rules spelled out in analysis plan

#### Differences from pre-data collection methods plan
  Any differences from what was described as the original plan, or “none”.


## Results


### Data preparation

Data preparation following the analysis plan.
	
```{r include=F}
###Data Preparation

####Load Relevant Libraries and Functions

####Import data

#### Data exclusion / filtering

#### Prepare data for analysis - create columns etc.
```

### Confirmatory analysis

The analyses as specified in the analysis plan.  

*Side-by-side graph with original graph is ideal here*

###Exploratory analyses

Any follow-up analyses desired (not required).  

## Discussion

### Summary of Replication Attempt

Open the discussion section with a paragraph summarizing the primary result from the confirmatory analysis and the assessment of whether it replicated, partially replicated, or failed to replicate the original result.  

### Commentary

Add open-ended commentary (if any) reflecting (a) insights from follow-up exploratory analysis, (b) assessment of the meaning of the replication (or not) - e.g., for a failure to replicate, are the differences between original and present study ones that definitely, plausibly, or are unlikely to have been moderators of the result, and (c) discussion of any objections or challenges raised by the current and original authors about the replication attempt.  None of these need to be long.
